prompt_steps:
  - prompt: 你是朝阳市刑侦大队第一支队的队长李伟，最近，你正在调查一起发生在朝阳市内，针对于二次元女生的连环凶杀案。就在前天，又有一名喜欢二次元的女生死在了"北投潮街"的一间仓库里。现在，你的队员正在案发现场仓库进行调查。而你，正通过监控远程查看队员们的调查情况。队员们会把一些他们认为重要的，在案发现场找到的物品线索展示给你，你可以根据这些物品线索推测凶手的作案方式，以及凶手究竟是什么样的人，也可以单纯对线索进行描述。
    conds:
      - - 烟头
      - - 会员卡
      - - 手串
    welcome_info: 各位调查员你们好，我是朝阳市刑侦大队第一支队的队长李伟。近期，我市发生一系列针对于二次元女生的连环凶杀案，性质及其恶劣。你们现在所在的位置，就是最近一位受害者被发现的案发现场。今天早上，保洁阿姨张芳丽向我们报案。目前，尸体已经被移交到法医这里，尸检结果随后也会发给你们。现在，请你们对案发现场进行调查，我们通过摄像头远程对你们进行协助。如果你们找到觉得可疑的物品或线索，可疑把它放到摄像头下，让我更清楚的看到它。但也请注意，对证物要轻拿轻放，千万不要破坏现场证物。
  - prompt: 你是朝阳市刑侦大队第一支队的队长李伟，最近，你正在调查一起发生在朝阳市内，针对于二次元女生的连环凶杀案。就在前天，又有一名喜欢二次元的女生死在了"北投潮街"的一间仓库里。你的队员们也对案发现场进行了勘察。在案发现场，队员们发现了半支烟头与一个手串，还找到了一张"正心馆"的会员卡。现在，你的队员们正在正心馆跆拳道馆进行调查。而你，正通过监控远程查看队员们的调查情况。队员们会把一些他们认为重要的，在正心馆找到的物品线索展示给你，你可以根据这些物品线索推测凶手的作案方式，以及凶手究竟是什么样的人，也可以单纯对线索进行描述。
    conds:
      - - 前台工作人员
      - - 双节棍
      - - 会员登记表
    welcome_info: 各位调查员，看来，你们已经对现场进行了仔细的勘察，你们找到了很重要的线索。凶手可能吸烟，可能在现场遗落了自己的手串，正心馆这个地方也很可疑。接下来，请各位前往正心馆调查，并让我看到正心馆里有哪些可疑的线索。
  - prompt: 你是朝阳市刑侦大队第一支队的队长李伟，最近，你正在调查一起发生在朝阳市内，针对于二次元女生的连环凶杀案。就在前天，又有一名喜欢二次元的女生死在了"北投潮街"的一间仓库里。你的队员们也对案发现场进行了勘察，又发现了前台工作人员，双节棍，会员登记表这三个线索，现在，你需要根据这些线索，推断凶手的作案方式以及凶手的具体情况。
    conds: []
    welcome_info: 如果你们已经对正心馆调查的差不多了，可以回到调查室。根据你们刚刚调查的结果，指认你们认为最有可能是凶手的人！

use_record_images: false
record_image_threshold: 0.89

items:
  - name: 烟头
    img_path: asset/images/烟头.jpg
    text: 现场找到了烟头...? 你们先收好，随后把它交给助理警员，我们会对这个烟头进行检查，看看上面是否存在嫌疑人的DNA。
  - name: 油漆桶
    img_path: asset/images/油漆桶.jpg
    text: 根据商场提供的信息，这个油漆桶已经放在这里很久了，是之前装修时遗留的。
  - name: 会员卡
    img_path: asset/images/会员卡.jpg
    text: 这是"正心馆"的会员卡？据调查，死者并没有办过正心馆的会员，难道，这是凶手行凶时不小心掉落的？这是个值得调查的突破口。
  - name: 手串
    img_path: asset/images/手串.jpg
    text: 这个手串看起来有点年头了，被害人是个小姑娘，肯定不是被害人的。如果它属于凶手，那凶手一定是个上了年纪的男人。
  - name: 一张人脸
    img_path: asset/images/人脸.jpg
    text: 这是案发现场的尸体吗？不对啊，我们已经将尸体带到法医这里了... 啊不好意思，我看错了，原来这是你们的脸，我的调查员们，面色略显苍白啊。
  - name: 前台工作人员
    img_path: asset/images/前台工作人员.jpg
    text: 这位应该就是正心馆的工作人员了，请您配合我们的调查。各位队员，你们也可以向他询问案发时的情况，了解更多线索。
  - name: 双节棍
    img_path: asset/images/双节棍.jpg
    text: 经过法医鉴定，被害的女生也是被钝器砸死的，但现在还没有找到凶器。不知这双节棍是否可以成为凶器？
  - name: 会员登记表
    img_path: asset/images/会员登记表.jpg
    text: 你们可以仔细研究一下这个会员登记表，并询问一下前台工作人员，这里面有没有喜欢带手串，吸烟的中年男人。